os:
  - linux
dist: trusty

language: c

before_script:
  - set -e
  - git clone -b devel --depth 1 git://github.com/nim-lang/nim nim-devel/
  - cd nim-devel
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin${PATH:+:$PATH}

script:
  - nim c koch
  - ./koch boot
  - cd ..
  - nim c -r nimcalcalpkg/tests/all
  - nim c -r nimcalcal
  - nim js -d:nodejs --threads:off -r nimcalcalpkg/tests/all
  - nim js -d:nodejs --threads:off -r nimcalcal.nim

notifications:
  email: "skilchen@bluewin.ch"
