os:
  - linux
dist: trusty

language: c

install:
  - |
      if [ ! -x nim-0.17.0/bin/nim ]
      then
        wget https://nim-lang.org/download/nim-0.17.0.tar.xz
        tar -xf nim-0.17.0.tar.xz
        cd nim-0.17.0
        sh build.sh
        rm -rf csources
        cd ..
      fi
      if [ ! -x nim-0.17.0/koch ]
      then
        cd nim-0.17.0
        bin/nim c koch
        ./koch boot -d:release
        ./koch nimble
        cd ..
      fi

before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/nim-0.17.0/bin:$PATH
  - nimble install strfmt -y

script:
  - nim c -r nimcalcal

cache:
  directories:
    - nim-0.17.0

notifications:
  email: "skilchen@bluewin.ch"
