os:
  - linux
dist: trusty

language: c

install:
  - |
      wget https://nim-lang.org/download/nim-0.17.0.tar.xz
      tar -xf nim-0.17.0.tar.xz
      cd nim-0.17.0
      sh build.sh
      cd ..

before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/nim-0.17.0/bin:$PATH

script:
  - nim c -r tests/all
  - nim c -r src/nimcalcal
  - nim js -d:nodejs --threads:off -r tests/all
  - nim js -d:nodejs --threads:off -r src/nimcalcal.nim

notifications:
  email: "skilchen@bluewin.ch"
