os:
  - linux
dist: trusty

language: c

install:
  - |
      if [ ! -x nim-0.17.0/bin/nim ]
      then
        wget https://nim-lang.org/download/nim-0.17.0.tar.xz
        tar -xf nim-0.17.0.tar.xz
        cd nim-0.17.0
        sh build.sh
        rm -rf csources
        cd ..
      fi

before_script:
  - set -e
  - set -x
  - export PATH=`pwd`/nim-0.17.0/bin:$PATH

script:
  - nim c -r nimblepkg/tests/all
  - nim c -r nimblepkg/nimcalcal
  - nim js -d:nodejs --threads:off -r nimcalcalpkg/tests/all
  - nim js -d:nodejs --threads:off -r nimcalcalkg/nimcalcal.nim

cache:
  directories:
    - nim-0.17.0

notifications:
  email: "skilchen@bluewin.ch"
